In [70]:
import pandas as pd
import glob
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

In [71]:
normal_pregnancy_files = glob.glob("Normal-Pregnancy/RNA-seq/*.txt")

In [72]:
for file in normal_pregnancy_files:
    print(file)

Normal-Pregnancy/RNA-seq/GSM4669903_Normal_2_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669901_Normal_2_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669895_Normal_1_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669914_Normal_5_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669938_Normal_9_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669928_Normal_7_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669926_Normal_7_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669935_Normal_9_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669930_Normal_8_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669929_Normal_8_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669912_Normal_4_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669897_Normal_1_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669899_Normal_2_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669907_Normal_3_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669918_Normal_5_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669917_Normal_5_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669931_Normal_8_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669900_Normal_2_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669905_Normal_3_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669924_Normal_7_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669902_Normal_2_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669916_Normal_5_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669896_Normal_1_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669937_Normal_9_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669920_Normal_6_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669925_Normal_7_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669936_Normal_9_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669911_Normal_4_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669904_Normal_3_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669927_Normal_7_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669913_Normal_4_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669898_Normal_1_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669921_Normal_6_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669932_Normal_8_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669919_Normal_6_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669906_Normal_3_3rdT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669922_Normal_6_delivery_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669909_Normal_4_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669934_Normal_9_1stT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669923_Normal_6_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669933_Normal_8_cordB_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669915_Normal_5_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669910_Normal_4_2ndT_Counts.txt
Normal-Pregnancy/RNA-seq/GSM4669908_Normal_3_cordB_Counts.txt

In [73]:
name_of_NP_files = normal_pregnancy_files[0].split("/")[2].split("_")[0]
print(name_of_NP_files)
NP_df = pd.read_csv(normal_pregnancy_files[0], delimiter="\t", header = None)
NP_df.columns = ["transcript", name_of_NP_files]

for file in normal_pregnancy_files[1:]: 
    name_of_NP_files = file.split("/")[2].split("_")[0]
#     print(name_of_NP_files)
    NP_df2 = pd.read_csv(file, delimiter="\t", header = None)
    NP_df2.columns = ["transcript", name_of_NP_files]
    NP_df = pd.concat([NP_df, NP_df2[name_of_NP_files]], axis = 1)

GSM4669903

In [74]:
NP_df

,transcript,GSM4669903,GSM4669901,GSM4669895,GSM4669914,GSM4669938,GSM4669928,GSM4669926,GSM4669935,GSM4669930,...,GSM4669919,GSM4669906,GSM4669922,GSM4669909,GSM4669934,GSM4669923,GSM4669933,GSM4669915,GSM4669910,GSM4669908
0,N_unmapped,9773198,25626203,10696201,14238121,7553957,25451045,6805347,7655192,9674080,...,6058345,8095646,7237229,12434735,11642763,9062191,6884146,18565629,9317256,6286573
1,N_multimapping,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,N_noFeature,3391310,6823385,771347,7593584,3119505,1891020,741212,2191184,4268451,...,8114943,2020184,7013259,8991695,3904038,6113825,5079224,8883187,2646773,2817967
3,N_ambiguous,41002,10321,55732,148246,94020,33618,60369,47124,136127,...,213569,75790,211689,422336,68054,212351,210458,19500,157879,129288
4,ENSG00000223972,0,0,0,0,0,0,6,0,0,...,31,0,50,31,0,7,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57735,ENSG00000272283,0,0,0,0,0,0,0,2,0,...,0,1,0,1,0,0,0,0,0,0
57736,ENSG00000160307,0,0,0,28,63,0,0,1,12,...,34,5,22,10,18,25,30,2,59,8
57737,ENSG00000160310,55,0,60,371,163,52,40,90,109,...,251,116,192,577,116,381,343,27,274,194
57738,ENSG00000230982,0,0,0,8,0,0,0,0,0,...,8,1,0,13,0,5,10,1,0,0
57739,ENSG00000212932,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [75]:
NP_df = NP_df.T ## switching the x and y axis
NP_df.drop(columns = [0, 1, 2, 3], inplace = True) ## dropping the unecessary columnns
NP_df = NP_df.T ## switching the x and y axis
NP_df.drop(columns= "transcript", axis=1, inplace = True)
NP_df = NP_df.T
NP_df

,4,5,6,7,8,9,10,11,12,13,...,57730,57731,57732,57733,57734,57735,57736,57737,57738,57739
GSM4669903,0,0,0,0,1,0,0,0,0,0,...,69,2,31,0,0,0,0,55,0,0
GSM4669901,0,0,0,0,0,0,0,0,0,1,...,3,0,0,0,0,0,0,0,0,0
GSM4669895,0,12,0,0,0,0,0,0,0,0,...,14,0,8,0,0,0,0,60,0,0
GSM4669914,0,0,0,0,0,0,0,0,0,1,...,84,0,224,0,0,0,28,371,8,0
GSM4669938,0,0,0,0,0,1,0,0,0,2,...,188,0,7,0,0,0,63,163,0,0
GSM4669928,0,0,0,0,0,0,0,0,0,0,...,9,0,1,0,0,0,0,52,0,0
GSM4669926,6,0,0,0,0,0,0,0,0,0,...,74,0,9,0,0,0,0,40,0,0
GSM4669935,0,0,0,0,3,0,0,0,0,0,...,54,0,23,0,0,2,1,90,0,0
GSM4669930,0,0,0,0,0,0,0,0,0,0,...,129,1,28,0,0,0,12,109,0,0
GSM4669929,0,0,0,0,0,0,0,0,0,0,...,16,0,8,0,0,0,0,146,0,0
GSM4669912,3,0,0,0,0,0,0,0,0,1,...,137,0,137,0,0,0,23,355,2,0
GSM4669897,20,1,0,0,1,0,0,0,0,0,...,47,0,27,0,0,0,0,42,1,0
GSM4669899,0,0,0,0,0,0,0,0,0,0,...,93,0,8,0,0,0,0,44,0,0
GSM4669907,0,0,0,0,0,0,0,0,0,0,...,106,1,54,0,0,0,8,131,0,0
GSM4669918,1,8,0,0,0,0,0,0,0,0,...,131,0,46,0,0,0,18,383,2,0
GSM4669917,0,1,0,0,0,0,0,0,0,0,...,84,0,90,4,0,0,12,374,0,0
GSM4669931,0,2,0,0,0,0,0,0,0,0,...,95,0,53,0,0,0,3,102,1,0
GSM4669900,0,0,0,0,0,0,0,0,0,0,...,12,0,5,0,0,0,8,97,0,0
GSM4669905,0,0,0,0,1,0,0,0,0,0,...,108,0,28,0,0,0,18,97,0,0
GSM4669924,0,0,0,0,5,0,0,0,0,0,...,112,0,44,0,0,0,3,121,8,0
GSM4669902,0,0,0,0,0,0,0,0,0,1,...,172,0,21,0,0,0,0,49,0,0
GSM4669916,0,2,0,0,0,0,0,0,0,2,...,442,0,272,0,0,0,30,570,0,0
GSM4669896,20,2,0,0,0,0,0,7,0,0,...,36,0,8,0,0,0,5,96,0,0
GSM4669937,0,0,0,0,0,0,0,0,0,0,...,91,0,70,0,0,0,37,78,0,0
GSM4669920,2,1,0,0,0,0,0,0,0,1,...,133,0,102,0,0,0,13,208,0,0
GSM4669925,0,0,0,0,5,0,0,0,0,0,...,54,0,33,0,0,0,25,173,0,0
GSM4669936,0,0,0,0,10,0,0,0,0,0,...,47,0,52,1,0,0,26,70,2,0
GSM4669911,0,1,0,0,0,0,0,0,0,0,...,176,0,130,0,0,0,26,422,0,0
GSM4669904,0,1,0,0,1,0,0,0,0,1,...,109,0,34,0,0,0,4,153,0,0
GSM4669927,0,0,0,0,0,0,0,0,0,0,...,27,33,79,0,0,0,0,62,0,0
GSM4669913,0,0,0,0,0,0,0,0,0,0,...,421,8,240,5,0,0,16,482,4,0
GSM4669898,3,0,0,0,0,0,0,0,0,0,...,90,0,4,0,0,0,10,97,0,0
GSM4669921,1,0,0,0,0,0,0,0,0,0,...,60,0,44,0,0,0,5,205,8,0
GSM4669932,3,1,0,0,0,0,0,0,0,0,...,78,0,22,0,0,0,4,156,0,0
GSM4669919,31,0,0,0,0,0,0,0,0,0,...,255,0,79,0,0,0,34,251,8,0
GSM4669906,0,0,0,0,0,0,0,4,0,0,...,77,0,27,0,0,1,5,116,1,0
GSM4669922,50,0,0,0,0,0,0,1,0,0,...,218,0,39,0,0,0,22,192,0,0
GSM4669909,31,2,0,0,0,0,0,0,0,5,...,296,8,224,9,1,1,10,577,13,0
GSM4669934,0,0,0,0,2,0,0,0,0,4,...,36,0,33,7,0,0,18,116,0,0
GSM4669923,7,3,0,0,0,0,0,0,0,0,...,339,0,126,1,0,0,25,381,5,0
GSM4669933,0,1,0,0,0,0,0,0,0,1,...,260,0,231,7,0,0,30,343,10,0
GSM4669915,0,0,0,0,2,0,0,0,0,0,...,6,0,3,3,0,0,2,27,1,0
GSM4669910,4,0,0,0,0,0,0,0,0,0,...,143,0,44,0,0,0,59,274,0,0
GSM4669908,0,0,1,0,0,0,0,10,0,0,...,144,0,37,0,0,0,8,194,0,0

In [36]:
NP_df.to_csv("normal_pregnancy_df.txt", index=False, sep="\t")

In [37]:
gestational_diabetes_files = glob.glob("Gestational-Diabetes/RNA-seq/*.txt")

In [38]:
for file in gestational_diabetes_files:
    print(file)

Gestational-Diabetes/RNA-seq/GSM4669955_GDM_4_3rdT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669946_GDM_2_delivery_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669945_GDM_2_2ndT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669944_GDM_2_1stT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669967_GDM_7_1stT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669960_GDM_5_delivery_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669959_GDM_5_3rdT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669947_GDM_2_cordB_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669949_GDM_3_2ndT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669948_GDM_3_1stT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669951_GDM_3_delivery_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669956_GDM_4_delivery_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669965_GDM_6_delivery_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669971_GDM_7_cordB_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669970_GDM_7_delivery_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669964_GDM_6_3rdT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669939_GDM_1_1stT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669940_GDM_1_2ndT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669968_GDM_7_2ndT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669961_GDM_5_cordB_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669958_GDM_5_2ndT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669942_GDM_1_delivery_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669952_GDM_3_cordB_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669954_GDM_4_2ndT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669966_GDM_6_cordB_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669963_GDM_6_2ndT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669962_GDM_6_1stT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669943_GDM_1_cordB_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669941_GDM_1_3rdT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669969_GDM_7_3rdT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669953_GDM_4_1stT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669957_GDM_5_1stT_Counts.txt
Gestational-Diabetes/RNA-seq/GSM4669950_GDM_3_3rdT_Counts.txt

In [39]:
name_of_GD_files = gestational_diabetes_files[0].split("/")[2].split("_")[0]
GD_df = pd.read_csv(gestational_diabetes_files[0], delimiter="\t", header = None)
GD_df.columns = ["transcript", name_of_GD_files]

for file in gestational_diabetes_files[1:]: 
    name_of_GD_files = file.split("/")[2].split("_")[0]
    GD_df2 = pd.read_csv(file, delimiter="\t", header = None)
    GD_df2.columns = ["transcript", name_of_GD_files]
    GD_df = pd.concat([GD_df, GD_df2[name_of_GD_files]], axis = 1)

In [40]:
GD_df

,transcript,GSM4669955,GSM4669946,GSM4669945,GSM4669944,GSM4669967,GSM4669960,GSM4669959,GSM4669947,GSM4669949,...,GSM4669954,GSM4669966,GSM4669963,GSM4669962,GSM4669943,GSM4669941,GSM4669969,GSM4669953,GSM4669957,GSM4669950
0,N_unmapped,14768386,21572512,21134386,21450301,14679243,15484615,5896302,15374403,17984099,...,13113920,1509148,13036749,10767159,18429766,17564571,13137667,17065574,3997509,17189469
1,N_multimapping,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,N_noFeature,1981005,3295245,3673181,4070928,5925714,4542404,1550318,2652519,2758511,...,2002501,1282602,1495153,1487398,5700082,4382293,6349499,1860489,2437958,3007601
3,N_ambiguous,62944,96304,58298,67653,62806,317806,123911,117444,57355,...,33696,2612,111405,105900,181055,52899,36729,43643,80237,59406
4,ENSG00000223972,1,3,0,0,11,20,2,0,0,...,0,0,0,13,0,43,4,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57735,ENSG00000272283,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57736,ENSG00000160307,3,13,0,0,4,11,0,18,10,...,0,0,1,19,26,5,0,0,0,1
57737,ENSG00000160310,71,123,110,65,95,309,116,182,76,...,102,0,157,105,414,77,50,36,70,69
57738,ENSG00000230982,0,0,0,0,1,2,0,6,0,...,0,0,0,3,0,0,5,0,0,0
57739,ENSG00000212932,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [41]:
GD_df = GD_df.T ## switching the x and y axis
GD_df.drop(columns = [0, 1, 2, 3], inplace = True) ## dropping the unecessary columnns
GD_df = GD_df.T ## switching the x and y axis
GD_df.drop(columns= "transcript", axis=1, inplace = True)
GD_df

,GSM4669955,GSM4669946,GSM4669945,GSM4669944,GSM4669967,GSM4669960,GSM4669959,GSM4669947,GSM4669949,GSM4669948,...,GSM4669954,GSM4669966,GSM4669963,GSM4669962,GSM4669943,GSM4669941,GSM4669969,GSM4669953,GSM4669957,GSM4669950
4,1,3,0,0,11,20,2,0,0,0,...,0,0,0,13,0,43,4,0,8,0
5,0,0,5,5,0,9,8,2,0,1,...,0,0,0,0,2,0,1,0,3,5
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,1,0,0,0,0,0,0,2,2,...,0,0,0,4,0,9,4,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57735,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
57736,3,13,0,0,4,11,0,18,10,2,...,0,0,1,19,26,5,0,0,0,1
57737,71,123,110,65,95,309,116,182,76,82,...,102,0,157,105,414,77,50,36,70,69
57738,0,0,0,0,1,2,0,6,0,0,...,0,0,0,3,0,0,5,0,0,0
57739,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
GD_df.to_csv("gestational_diabetes_df.txt", index=False, sep="\t")

In [43]:
chronic_hypertension_files = glob.glob("Chronic-Hypertension/RNA-seq/*.txt")

In [44]:
for file in chronic_hypertension_files:
    print(file)

Chronic-Hypertension/RNA-seq/GSM4670017_cHTN_2_1stT_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670013_cHTN_1_2ndT_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670020_cHTN_2_delivery_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670014_cHTN_1_3rdT_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670015_cHTN_1_delivery_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670018_cHTN_2_2ndT_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670012_cHTN_1_1stT_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670019_cHTN_2_3rdT_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670021_cHTN_2_cordB_Counts.txt
Chronic-Hypertension/RNA-seq/GSM4670016_cHTN_1_CordB_Counts.txt

In [45]:
name_of_CH_files = chronic_hypertension_files[0].split("/")[2].split("_")[0]
CH_df = pd.read_csv(chronic_hypertension_files[0], delimiter="\t", header = None)
CH_df.columns = ["transcript", name_of_CH_files]

for file in chronic_hypertension_files[1:]: 
    name_of_CH_files = file.split("/")[2].split("_")[0]
    CH_df2 = pd.read_csv(file, delimiter="\t", header = None)
    CH_df2.columns = ["transcript", name_of_CH_files]
    CH_df = pd.concat([CH_df, CH_df2[name_of_CH_files]], axis = 1)

In [46]:
CH_df

,transcript,GSM4670017,GSM4670013,GSM4670020,GSM4670014,GSM4670015,GSM4670018,GSM4670012,GSM4670019,GSM4670021,GSM4670016
0,N_unmapped,16652912,14014885,23628943,19618464,21813444,18273107,14874710,18501088,20373785,17478766
1,N_multimapping,0,0,0,0,0,0,0,0,0,0
2,N_noFeature,5284432,1792926,8990879,2827272,4210311,7162859,2395142,10739960,10744749,3893833
3,N_ambiguous,75699,118628,85445,93358,87530,91531,96654,83939,120613,132083
4,ENSG00000223972,0,0,3,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...
57735,ENSG00000272283,0,0,2,0,0,0,0,0,0,0
57736,ENSG00000160307,8,28,5,3,2,2,30,5,8,38
57737,ENSG00000160310,73,155,135,146,101,90,134,139,175,240
57738,ENSG00000230982,4,7,4,0,0,0,0,3,1,0
57739,ENSG00000212932,0,0,0,0,0,0,0,0,0,0

In [47]:
CH_df = CH_df.T ## switching the x and y axis
CH_df.drop(columns = [0, 1, 2, 3], inplace = True) ## dropping the unecessary columnns
CH_df = CH_df.T ## switching the x and y axis
CH_df.drop(columns= "transcript", axis=1, inplace = True)
CH_df

,GSM4670017,GSM4670013,GSM4670020,GSM4670014,GSM4670015,GSM4670018,GSM4670012,GSM4670019,GSM4670021,GSM4670016
4,0,0,3,0,0,0,0,0,0,2
5,0,0,0,0,0,0,4,2,2,3
6,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0
8,0,0,7,0,0,11,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...
57735,0,0,2,0,0,0,0,0,0,0
57736,8,28,5,3,2,2,30,5,8,38
57737,73,155,135,146,101,90,134,139,175,240
57738,4,7,4,0,0,0,0,3,1,0
57739,0,0,0,0,0,0,0,0,0,0

In [48]:
CH_df.to_csv("chronic_hypertension_df.txt", index=False, sep="\t")

In [49]:
preeclampsia_files = glob.glob("Preeclampsia/RNA-seq/*.txt")

In [50]:
for file in preeclampsia_files:
    print(file)

Preeclampsia/RNA-seq/GSM4669998_PreX_gHTN_6_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4669996_PreX_gHTN_5_cordB_Counts.txt
Preeclampsia/RNA-seq/GSM4669992_PreX_gHTN_5_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4670007_PreX_gHTN_8_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4669988_PreX_gHTN_4_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4670002_PreX_gHTN_7_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4670000_PreX_gHTN_6_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669981_PreX_gHTN_2_cordB_Counts.txt
Preeclampsia/RNA-seq/GSM4670005_PreX_gHTN_7_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669977_PreX_gHTN_2_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4669973_PreX_gHTN_1_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4669989_PreX_gHTN_4_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4669994_PreX_gHTN_5_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4669983_PreX_gHTN_3_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4669999_PreX_gHTN_6_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4670004_PreX_gHTN_7_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4669990_PreX_gHTN_4_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669995_PreX_gHTN_5_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669976_PreX_gHTN_1_cordB_Counts.txt
Preeclampsia/RNA-seq/GSM4670006_PreX_gHTN_7_cordB_Counts.txt
Preeclampsia/RNA-seq/GSM4669972_PreX_gHTN_1_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4670011_PreX_gHTN_8_cordB_Counts.txt
Preeclampsia/RNA-seq/GSM4669987_PreX_gHTN_4_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4670008_PreX_gHTN_8_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4669978_PreX_gHTN_2_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4669982_PreX_gHTN_3_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4669975_PreX_gHTN_1_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669997_PreX_gHTN_6_1stT_Counts.txt
Preeclampsia/RNA-seq/GSM4670001_PreX_gHTN_6_cordB_Counts.txt
Preeclampsia/RNA-seq/GSM4669974_PreX_gHTN_1_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4669991_PreX_gHTN_4_cordB_Counts.txt
Preeclampsia/RNA-seq/GSM4669993_PreX_gHTN_5_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4669980_PreX_gHTN_2_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669984_PreX_gHTN_3_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4670003_PreX_gHTN_7_2ndT_Counts.txt
Preeclampsia/RNA-seq/GSM4670009_PreX_gHTN_8_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4669979_PreX_gHTN_2_3rdT_Counts.txt
Preeclampsia/RNA-seq/GSM4670010_PreX_gHTN_8_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669985_PreX_gHTN_3_delivery_Counts.txt
Preeclampsia/RNA-seq/GSM4669986_PreX_gHTN_3_cordB_Counts.txt

In [51]:
name_of_P_files = preeclampsia_files[0].split("/")[2].split("_")[0]
P_df = pd.read_csv(preeclampsia_files[0], delimiter="\t", header = None)
P_df.columns = ["transcript", name_of_P_files]

for file in preeclampsia_files[1:]: 
    name_of_P_files = file.split("/")[2].split("_")[0]
    P_df2 = pd.read_csv(file, delimiter="\t", header = None)
    P_df2.columns = ["transcript", name_of_P_files]
    P_df = pd.concat([P_df, P_df2[name_of_P_files]], axis = 1)

In [52]:
P_df

,transcript,GSM4669998,GSM4669996,GSM4669992,GSM4670007,GSM4669988,GSM4670002,GSM4670000,GSM4669981,GSM4670005,...,GSM4669991,GSM4669993,GSM4669980,GSM4669984,GSM4670003,GSM4670009,GSM4669979,GSM4670010,GSM4669985,GSM4669986
0,N_unmapped,16471356,6675255,15276429,18816816,12382720,17913658,12865252,9436671,20691978,...,11066719,16414259,8534692,10579678,25384160,16161393,10098042,17625158,10809854,15559560
1,N_multimapping,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,N_noFeature,2482224,1660592,3167790,1417245,2256350,4707346,1450987,1592690,7906206,...,4166530,5007211,2010433,3945093,4807483,2311088,3215129,1610187,6611294,5209304
3,N_ambiguous,102762,112831,90006,48381,39584,66447,134653,142509,48201,...,32045,76950,98205,124913,52882,86464,122672,48359,132631,136272
4,ENSG00000223972,3,0,0,6,19,1,6,9,0,...,0,0,3,0,1,34,0,11,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57735,ENSG00000272283,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57736,ENSG00000160307,0,13,7,0,0,2,0,13,9,...,3,13,0,6,6,1,1,0,6,4
57737,ENSG00000160310,135,179,132,47,20,76,230,146,56,...,22,135,55,175,74,109,122,56,184,201
57738,ENSG00000230982,0,3,1,0,0,0,0,0,0,...,0,0,3,0,2,1,0,0,0,0
57739,ENSG00000212932,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0

In [53]:
P_df = P_df.T ## switching the x and y axis
P_df.drop(columns = [0, 1, 2, 3], inplace = True) ## dropping the unecessary columnns
P_df = P_df.T ## switching the x and y axis
P_df.drop(columns= "transcript", axis=1, inplace = True)
P_df

,GSM4669998,GSM4669996,GSM4669992,GSM4670007,GSM4669988,GSM4670002,GSM4670000,GSM4669981,GSM4670005,GSM4669977,...,GSM4669991,GSM4669993,GSM4669980,GSM4669984,GSM4670003,GSM4670009,GSM4669979,GSM4670010,GSM4669985,GSM4669986
4,3,0,0,6,19,1,6,9,0,1,...,0,0,3,0,1,34,0,11,2,0
5,9,0,1,0,0,1,0,2,1,0,...,0,0,1,0,0,2,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,6,0,0,2,0,...,0,3,0,0,8,0,0,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57735,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57736,0,13,7,0,0,2,0,13,9,0,...,3,13,0,6,6,1,1,0,6,4
57737,135,179,132,47,20,76,230,146,56,30,...,22,135,55,175,74,109,122,56,184,201
57738,0,3,1,0,0,0,0,0,0,0,...,0,0,3,0,2,1,0,0,0,0
57739,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
P_df.to_csv("preeclampsia_df.txt", index=False, sep="\t")

In [55]:
non_pregnant_files = glob.glob("Non-Pregnant/RNA-seq/*.txt")

In [56]:
for file in non_pregnant_files:
    print(file)

Non-Pregnant/RNA-seq/GSM4670025_NP_4_Counts.txt
Non-Pregnant/RNA-seq/GSM4670026_NP_5_Counts.txt
Non-Pregnant/RNA-seq/GSM4670022_NP_1_Counts.txt
Non-Pregnant/RNA-seq/GSM4670024_NP_3_Counts.txt
Non-Pregnant/RNA-seq/GSM4670028_NP_7_Counts.txt
Non-Pregnant/RNA-seq/GSM4670027_NP_6_Counts.txt
Non-Pregnant/RNA-seq/GSM4670023_NP_2_Counts.txt

In [57]:
name_of_NonP_files = non_pregnant_files[0].split("/")[2].split("_")[0]
NonP_df = pd.read_csv(non_pregnant_files[0], delimiter="\t", header = None)
NonP_df.columns = ["transcript", name_of_NonP_files]

for file in non_pregnant_files[1:]: 
    name_of_NonP_files = file.split("/")[2].split("_")[0]
    NonP_df2 = pd.read_csv(file, delimiter="\t", header = None)
    NonP_df2.columns = ["transcript", name_of_NonP_files]
    NonP_df = pd.concat([NonP_df, NonP_df2[name_of_NonP_files]], axis = 1)

In [58]:
NonP_df

,transcript,GSM4670025,GSM4670026,GSM4670022,GSM4670024,GSM4670028,GSM4670027,GSM4670023
0,N_unmapped,9289303,11596904,11745613,19089543,5773775,16910437,9252796
1,N_multimapping,0,0,0,0,0,0,0
2,N_noFeature,1933206,1809457,2081674,11237910,1857087,3767596,2162411
3,N_ambiguous,86059,119723,122214,10239,104226,122198,88093
4,ENSG00000223972,0,0,0,0,4,1,0
...,...,...,...,...,...,...,...,...
57735,ENSG00000272283,0,0,0,0,0,0,0
57736,ENSG00000160307,2,12,22,0,18,37,25
57737,ENSG00000160310,115,165,162,48,121,216,142
57738,ENSG00000230982,0,0,1,0,0,0,2
57739,ENSG00000212932,0,0,0,0,0,0,0

In [59]:
NonP_df = NonP_df.T ## switching the x and y axis
NonP_df.drop(columns = [0, 1, 2, 3], inplace = True) ## dropping the unecessary columnns
NonP_df = NonP_df.T ## switching the x and y axis
NonP_df.drop(columns= "transcript", axis=1, inplace = True)
NonP_df

,GSM4670025,GSM4670026,GSM4670022,GSM4670024,GSM4670028,GSM4670027,GSM4670023
4,0,0,0,0,4,1,0
5,0,0,0,0,0,2,1
6,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0
8,0,0,0,14,0,0,3
...,...,...,...,...,...,...,...
57735,0,0,0,0,0,0,0
57736,2,12,22,0,18,37,25
57737,115,165,162,48,121,216,142
57738,0,0,1,0,0,0,2
57739,0,0,0,0,0,0,0

In [60]:
NonP_df.to_csv("non_pregnant_df.txt", index=False, sep="\t")